### ISSUE TITLE
error on import

### ISSUE THREAD

**Issue by codestar12** [moskomule/anatome#9]
called 

ran 

`import anatome`

Traceback (most recent call last):

  File "/home/cody/miniconda3/envs/RepDist/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3437, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-1-a04db79890a8>", line 1, in <module>
    import anatome

  File "/home/cody/miniconda3/envs/RepDist/lib/python3.7/site-packages/anatome/__init__.py", line 1, in <module>
    from .similarity import SimilarityHook

  File "<fstring>", line 1
    (x.size(0)=)
              ^
SyntaxError: invalid syntax

I have anatome==0.0.1
I can provide my environment info if needed but the error looks pretty clear.

**Comment by codestar12** [comment]
can we change those f-strings to support 3.7?

**Comment by moskomule** [comment]
This library only supports Python 3.8 or higher. PRs are welcome.

**Comment by codestar12** [comment]
It's a super simple change to make it 3.7 comparable. I cloned it and fixed it on my machine. I can put the pull request in after my paper deadline. I guess it depends on if wanting to support 3.7 is something you want to do.
